[versions]
agp = "9.0.0"
kotlin = "2.3.0"
compose = "1.11.0-alpha02"
androidx-appcompat = "1.7.1"
activity-compose = "1.13.0-alpha01"
datetime = "0.7.1"
material-kolor = "5.0.0-alpha05"
decompose = "3.4.0"
essenty = "2.5.0"
serialization = "1.10.0"
atomicfu = "0.31.0"
#maven-publish="0.25.3"li

[libraries]
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }
activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity-compose" }
datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "datetime" }
material-kolor = { module = "com.materialkolor:material-kolor", version.ref = "material-kolor" }
decompose-core = { module = "com.arkivanov.decompose:decompose", version.ref = "decompose" }
decompose-compose = { module = "com.arkivanov.decompose:extensions-compose", version.ref = "decompose" }
essenty = { module = "com.arkivanov.essenty:lifecycle", version.ref = "essenty" }
serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization" }
atomicfuPlugin = { module = "org.jetbrains.kotlinx:atomicfu-gradle-plugin", version.ref = "atomicfu" }
atomicfu = { module = "org.jetbrains.kotlinx:atomicfu", version.ref = "atomicfu" }

material-icons-core = { group = "org.jetbrains.compose.material", name = "material-icons-core", version = "1.7.3" }

compose-runtime = { group = "org.jetbrains.compose.runtime", name = "runtime", version.ref = "compose" }
compose-foundation = { group = "org.jetbrains.compose.foundation", name = "foundation", version.ref = "compose" }
compose-ui = { group = "org.jetbrains.compose.ui", name = "ui", version.ref = "compose" }
compose-uiutil = {   group = "org.jetbrains.compose.ui", name = "ui-util", version.ref = "compose" }
compose-animation = { group = "org.jetbrains.compose.animation", name = "animation", version.ref = "compose" }
compose-material = { group = "org.jetbrains.compose.material", name = "material", version.ref = "compose" }
compose-material3 = { group = "org.jetbrains.compose.material3", name = "material3", version.ref = "compose" }
compose-material-icons-extended = { group = "org.jetbrains.compose.material", name = "material-icons-extended", version = "1.7.3" }

kotlin-gradle-plugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
android-gradle-plugin = { group = "com.android.tools.build", name = "gradle", version.ref = "agp" }
vanniktech-maven-publish-plugin = { group = "com.vanniktech", name = "gradle-maven-publish-plugin", version = "0.36.0" }
dokka-gradle-plugin = { group = "org.jetbrains.dokka", name = "org.jetbrains.dokka.gradle.plugin", version = "2.1.0" }

[plugins]
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
cocoapods = { id = "org.jetbrains.kotlin.native.cocoapods", version.ref = "kotlin" }
composeJB = { id = "org.jetbrains.compose", version.ref = "compose" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }

android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
#maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "maven-publish" }
